nav:
    - Smartpaper: index.md
    - Implementation:
        - Genesis State: state.md
        - params.md
        - updates.md
        - config.md
    - Notebooks:
        - Simple Analysis: simple-analysis.ipynb
plugins:
    - mkdocs-jupyter:
        ignore_h1_titles: True