nav:
    - Smart Paper: index.md
    - Implementation:
        - state.md
        - params.md
        - updates.md
        - config.md
    - Notebooks:
        - Simple Analysis: simple-analysis.ipynb
        - Extended Analysis: extended-analysis.ipynb
    - Additional Resources:
        - Uniswap Whitepaper (v3): https://uniswap.org/whitepaper-v3.pdf
        - Model Repository: https://github.com/tylerdmace/cadcad-uniswap
plugins:
    - mkdocs-jupyter:
        ignore_h1_titles: True
extra_css:
    - css/analysis.css
extra_javascript:
    - js/d3@7.js
    - js/analysis.js
    - js/iframeresizer.min.js