nav:
    - Smartpaper: index.md
    - Genesis State: state.md
    - params.md
    - updates.md
    - config.md
    - "Notebook: Simple": simple-analysis.ipynb
plugins:
    - mkdocs-jupyter:
        ignore_h1_titles: True