nav:
    - Smart Paper: index.md
    - Implementation:
        - Genesis State: state.md
        - params.md
        - updates.md
        - config.md
    - Notebooks:
        - Simple Analysis: simple-analysis.ipynb
    - Additional Resources:
        - Uniswap Whitepaper (v3): https://uniswap.org/whitepaper-v3.pdf
plugins:
    - mkdocs-jupyter:
        ignore_h1_titles: True